name: Release Packages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    if: >-
      ${{ github.event.pull_request.merged == true &&
          github.event.pull_request.base.ref == 'main' &&
          startsWith(github.event.pull_request.title, 'RELEASES:') || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout merge commit
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore AutoInject.sln

       - name: Build solution
        run: dotnet build AutoInject.sln --configuration Release --no-restore

      - name: Run unit tests
        run: dotnet test AutoInject.Tests.Unit/AutoInject.Tests.Unit.csproj --configuration Release --no-build

      - name: Pack AutoInject package
        run: dotnet pack AutoInject/AutoInject.csproj --configuration Release --output ./artifacts --no-build

      - name: Publish package to NuGet.org
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push "artifacts/*.nupkg" --source https://api.nuget.org/v3/index.json --api-key "$NUGET_API_KEY" --skip-duplicate
